### PR TITLE
Rebase to noble, add encryption support (master)

### PR DESCRIPTION
**Pull request by thespad**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-duplicati/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:
This will fail until 2.0.9 hits stable.

### CODE REVIEW

**Comment by kenkendk** [comment]
FYI: Duplicati removed the auto-assigned settings encryption key in v2.0.9.106, so only version 2.0.9.105 is using a system-derived encryption key.
The change was rolled back after we discovered the device key was not based on sufficiently random data (in many case, it was based on an empty string).

The changes in this PR are thus not required for Duplicati 2.0.9.106+ but increases security by specifying a settings encryption key.

**Comment by aptalca** [comment]
Needs arm64 binary name updated as well

**Comment by aptalca** [comment]
Unzip adds a subfolder so we need a mv after

**Comment by thespad** [comment]
You'd think I'd have noticed these things when I did the PR months ago, as I was mostly copying from the dev branch which is already correct.

**Review by aptalca — APPROVED** [review]

**Pull request merged**
